apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  clusterIP: 10.96.203.174
  externalIPs:
  - 192.168.100.173
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
